variable "env_name" {}
variable "ami_name" {}
variable "sg_name" {}
variable "instance_type" {}
variable "root_volume_size" {}
variable "name" {}
variable "domain_name" {}
variable "internal" {}
variable "vault_token" {}