name: Apply
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  plan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Plans Infra
        run: make test-plan TOKEN="${{ secrets.VAULT_TOKEN }}"

  provision:
    needs: plan
    runs-on: self-hosted
    environment: test-approval
    steps:
      - uses: actions/checkout@v4
      - name: Provisions Test Infra
        run: make test-apply TOKEN="${{ secrets.VAULT_TOKEN }}"
