name: Apply
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Plans Infra
        run: make test-plan TOKEN={{ secrets.VAULT_TOKEN }} 

      - name: Provisions Infra
        run: make test-apply TOKEN={{ secrets.VAULT_TOKEN }} 
