name: Apply
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Destroys Infra
        run: echo hello #bash init.sh destroy test ${{ secrets.VAULT_TOKEN }}
